from tkinter.constants import *
import tkinter.ttk as ttk
from tkinter import *
import tkinter as tk
import GUIFunctions
import Utils


class main_gui:
    def __init__(self, top):
        top.geometry("400x250+398+236")
        top.minsize(120, 1)
        top.maxsize(5140, 1197)
        top.resizable(0, 0)
        top.title("Pysubstitute")
        top.iconbitmap(Utils.get_resources_path("resources\\icon\\app_icon.ico"))
        top.configure(background="#808080")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.top = top

        self.label_title = tk.Label(self.top)
        self.label_title.place(relx=0.125, rely=0.024, height=32, width=304)
        self.label_title.configure(activebackground="#f9f9f9")
        self.label_title.configure(activeforeground="black")
        self.label_title.configure(background="#808080")
        self.label_title.configure(compound='left')
        self.label_title.configure(disabledforeground="#a3a3a3")
        self.label_title.configure(font="-family {Arial} -size 14 -weight bold")
        self.label_title.configure(foreground="#000000")
        self.label_title.configure(highlightbackground="#d9d9d9")
        self.label_title.configure(highlightcolor="black")
        self.label_title.configure(text="Pysubstitute")

        self.label_old_string = tk.Label(self.top)
        self.label_old_string.place(relx=0.05, rely=0.176, height=19, width=164)
        self.label_old_string.configure(activebackground="#f9f9f9")
        self.label_old_string.configure(activeforeground="black")
        self.label_old_string.configure(background="#808080")
        self.label_old_string.configure(compound='left')
        self.label_old_string.configure(disabledforeground="#a3a3a3")
        self.label_old_string.configure(foreground="#000000")
        self.label_old_string.configure(highlightbackground="#d9d9d9")
        self.label_old_string.configure(highlightcolor="black")
        self.label_old_string.configure(text="Old string")

        self.label_new_string = tk.Label(self.top)
        self.label_new_string.place(relx=0.525, rely=0.176, height=19, width=164)
        self.label_new_string.configure(activebackground="#f9f9f9")
        self.label_new_string.configure(activeforeground="black")
        self.label_new_string.configure(background="#808080")
        self.label_new_string.configure(compound='left')
        self.label_new_string.configure(disabledforeground="#a3a3a3")
        self.label_new_string.configure(foreground="#000000")
        self.label_new_string.configure(highlightbackground="#d9d9d9")
        self.label_new_string.configure(highlightcolor="black")
        self.label_new_string.configure(text="New string")

        self.entry_old_string = tk.Entry(self.top)
        self.entry_old_string.place(relx=0.05, rely=0.252, height=30, relwidth=0.41)
        self.entry_old_string.configure(background="white")
        self.entry_old_string.configure(disabledforeground="#a3a3a3")
        self.entry_old_string.configure(font="TkFixedFont")
        self.entry_old_string.configure(foreground="#000000")
        self.entry_old_string.configure(highlightbackground="#d9d9d9")
        self.entry_old_string.configure(highlightcolor="black")
        self.entry_old_string.configure(insertbackground="black")
        self.entry_old_string.configure(selectbackground="gray")
        self.entry_old_string.configure(selectforeground="white")

        self.entry_new_string = tk.Entry(self.top)
        self.entry_new_string.place(relx=0.525, rely=0.252, height=30, relwidth=0.41)
        self.entry_new_string.configure(background="white")
        self.entry_new_string.configure(disabledforeground="#a3a3a3")
        self.entry_new_string.configure(font="TkFixedFont")
        self.entry_new_string.configure(foreground="#000000")
        self.entry_new_string.configure(highlightbackground="#d9d9d9")
        self.entry_new_string.configure(highlightcolor="black")
        self.entry_new_string.configure(insertbackground="black")
        self.entry_new_string.configure(selectbackground="gray")
        self.entry_new_string.configure(selectforeground="white")

        self.label_target_folder = tk.Label(self.top)
        self.label_target_folder.place(relx=0.05, rely=0.370, height=25, width=314)
        self.label_target_folder.configure(activebackground="#f9f9f9")
        self.label_target_folder.configure(activeforeground="black")
        self.label_target_folder.configure(background="#808080")
        self.label_target_folder.configure(compound='left')
        self.label_target_folder.configure(disabledforeground="#a3a3a3")
        self.label_target_folder.configure(foreground="#000000")
        self.label_target_folder.configure(highlightbackground="#d9d9d9")
        self.label_target_folder.configure(highlightcolor="black")
        self.label_target_folder.configure(text="Target folder")

        self.entry_target_folder = tk.Entry(self.top)
        self.entry_target_folder.place(relx=0.05, rely=0.468, height=30, relwidth=0.785)
        self.entry_target_folder.configure(background="white")
        self.entry_target_folder.configure(disabledforeground="#a3a3a3")
        self.entry_target_folder.configure(font="TkFixedFont")
        self.entry_target_folder.configure(foreground="#000000")
        self.entry_target_folder.configure(highlightbackground="#d9d9d9")
        self.entry_target_folder.configure(highlightcolor="black")
        self.entry_target_folder.configure(insertbackground="black")
        self.entry_target_folder.configure(selectbackground="gray")
        self.entry_target_folder.configure(selectforeground="white")

        self.button_browse = tk.Button(self.top)
        self.button_browse.place(relx=0.863, rely=0.468, height=30, width=30)
        self.button_browse.configure(activebackground="#ececec")
        self.button_browse.configure(activeforeground="#000000")
        self.button_browse.configure(background="#d9d9d9")
        self.button_browse.configure(compound='left')
        self.button_browse.configure(disabledforeground="#a3a3a3")
        self.button_browse.configure(foreground="#000000")
        self.button_browse.configure(highlightbackground="#d9d9d9")
        self.button_browse.configure(highlightcolor="black")
        self.button_browse.configure(pady="0")
        self.browse_picture = PhotoImage(file=Utils.get_resources_path("resources\\pictures\\browse.png"))
        self.button_browse.configure(image=self.browse_picture)
        self.button_browse.configure(command=lambda: GUIFunctions.browse_target_folder(self.entry_target_folder))

        self.button_github = tk.Button(self.top)
        self.button_github.place(relx=0.05, rely=0.68, height=60, width=60)
        self.button_github.configure(activebackground="#ececec")
        self.button_github.configure(activeforeground="#000000")
        self.button_github.configure(background="#d9d9d9")
        self.button_github.configure(compound='left')
        self.button_github.configure(disabledforeground="#a3a3a3")
        self.button_github.configure(foreground="#000000")
        self.button_github.configure(highlightbackground="#d9d9d9")
        self.button_github.configure(highlightcolor="black")
        self.button_github.configure(pady="0")
        self.button_github.configure(text="Github")
        self.button_github.configure(command=GUIFunctions.browse_to_github)

        self.button_proceed = tk.Button(self.top)
        self.button_proceed.place(relx=0.25, rely=0.68, height=60, width=120)
        self.button_proceed.configure(activebackground="#ececec")
        self.button_proceed.configure(activeforeground="#000000")
        self.button_proceed.configure(background="#d9d9d9")
        self.button_proceed.configure(compound='left')
        self.button_proceed.configure(disabledforeground="#a3a3a3")
        self.button_proceed.configure(foreground="#000000")
        self.button_proceed.configure(highlightbackground="#d9d9d9")
        self.button_proceed.configure(highlightcolor="black")
        self.button_proceed.configure(pady="0")
        self.button_proceed.configure(text="Proceed!")
        self.button_proceed.configure(command=lambda: GUIFunctions.proceed(self.entry_old_string, self.entry_new_string,
                                                                           self.entry_target_folder))

        self.label_credits = tk.Label(self.top)
        self.label_credits.place(relx=0.65, rely=0.70, height=50, width=120)
        self.label_credits.configure(activebackground="#f9f9f9")
        self.label_credits.configure(activeforeground="black")
        self.label_credits.configure(anchor='e')
        self.label_credits.configure(background="#808080")
        self.label_credits.configure(compound='left')
        self.label_credits.configure(disabledforeground="#a3a3a3")
        self.label_credits.configure(foreground="#000000")
        self.label_credits.configure(highlightbackground="#d9d9d9")
        self.label_credits.configure(highlightcolor="black")
        self.label_credits.configure(text="MIT License \n Created by Disk_MTH")
